### ISSUE TITLE
Investigate pointing SL domains at CloudFront

### ISSUE THREAD

**Issue by oriondean** [ScottLogic/StockFlux#1097]
To answer:

* Is it possible to point A records at our CloudFront distribution?
* Use a RetentionPolicy to ensure distribution is never deleted by can be updated?
* Use another domain that we control inbetween SL and CloudFront?

**Comment by jrhenderson1988** [comment]
> Is it possible to point A records at our CloudFront distribution?

There's doesn't seem to be a way we can use A records to point at our CloudFront distribution because there's no static set of IP addresses to point at. AWS seems to only offer using a CNAME DNS record for custom domains. Using Route 53 allows the zone apex to be set to be an alias of a CloudFront distribution such that a domain can point to the distribution without using a CNAME record. This only works for parent/root domains.

> Use a RetentionPolicy to ensure distribution is never deleted by can be updated?

It is possible to use a *DeletionPolicy* with a value of `Retain` to ensure that the CloudFront distribution (and its Origin Policy for talking to S3) persist, even following the deletion of a stack. Providing that we never delete our stacks once created, we can use CloudFormation to make updates to the resources, including CloudFront, by modifying the template and triggering an update. Once created, a stack for a permanent stage such as "production" (or possibly "dev"/"staging") is almost *never* deleted.

> Use another domain that we control inbetween SL and CloudFront?

I've not been able to test this out properly, but it seems that [creating a CNAME to CNAME chain is possible](https://serverfault.com/questions/309651/is-a-cname-to-cname-chain-allowed). This would make it possible to use a CNAME to point `stockflux.scottlogic.com` at a domain that we control ourselves (Possibly in Route 53) and then use a CNAME in that intermediate domain to point at our CloudFront distribution. This shifts the burden of updating DNS to ourselves, rather than the IT department if we delete/re-create stacks and end up with new CloudFront distributions.

---

I would personally prefer to go for the second option of using a *DeletionPolicy* to ensure that our CloudFront distribution (and our DynamoDB database) persist any stack deletions. This would only function as a safeguard against losing our DNS -> CDN mapping and database. In the event that our stack was deleted we would need to make significant changes to our CloudFormation template to get it to work with our persisted DynamoDB table and CloudFront distribution.

Once created and considered *live* in an environment such as *production* (or *dev*), stacks should **never** be deleted. This can be enforced by adding termination protection to our stacks to avoid accidental deletion.

An argument could be made to remove CloudFront from our stack altogether and to write our CloudFormation template to work around an existing distribution. However, I believe that this has some significant drawbacks:

- It adds complexity in that we need to adapt our CloudFormation templates to account for existing resources. We'd need to specify resource names (or possibly ARNs) when creating our stacks and it may limit what we are able to query about those existing resources.
- Maintaining our distribution would become a manual task. Any changes to our configuration would need to be done by hand and replicated to the distributions for our other stages too, which can be a slow and error prone process.
- We would partially lose a significant benefit of CloudFormation - automation. Spinning up a complete new stack would require manually creating a CloudFront distribution before manually specifying it when building the stack. In addition to being slow, this process also risks accidentally making changes to the wrong distribution. If someone was to specify the identifier of the wrong CloudFront distribution, it's possible that the stack creation would modify the wrong resource. For instance, this could result in the production distribution being modified to point at an ad-hoc stack. When this stack is deleted, the production CloudFront distribution could then end up pointing at nothing.

Does anyone have any other thoughts on this? @markjose @oriondean

**Comment by oriondean** [comment]
Option two sounds like the most pragmatic approach, option three would be nice but i feel comes at a cost of increased complexity (having to maintain and sync two CNAMEs).

As long as we document the restrictions imposed upon us by option two (e.g. can't tear down stack unless we repoint CNAME for new deployment) i'm happy going with this option.

**Comment by markjose** [comment]
Let's do option 2 and see how we get on. What are the implications if we were to spin up a new environment? Would the new stage affect cloudfront?

**Comment by jrhenderson1988** [comment]
Sounds good. As discussed in person, we would have one CloudFormation template that is used to spin up completely independent stacks for each environment/stage. This means that spinning up a new stack for a different stage, or even an ad-hoc stack for experimental purposes, should never affect an existing stack.

I'll close this issue and create a new one for the work to get option 2 implemented.
