### ISSUE TITLE
When tearing out windows they do not always appear at the correct location

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/StockFlux#507]
If you tear out a tile, the new window should appear so that the mouse is still over the tile.

If you tear out a tile so that the new window is cropped by the screen bounds, the window is re-positioned so that it is entirely on-screen. This feels very odd (and is not what chrome does!)

**Comment by WPFerg** [comment]
The reason for this is because if you try to tear out to the top left corner, you'd end up with a window offset such that you would be unable to move it afterwards, this compensation ensures that you can always move the window. Should this compensation *only* happen when tearing out to the top/left?

**Comment by owennw** [comment]
Similarly to the RHS of the screen -- as there's not draggable area above the sidebar the window would be stuck.

**Comment by ColinEberhardt** [comment]
From discussing with Rui, he feels that it makes sense to extend the draggable title bar area to include the favourites / search. As a result, we shouldn't have to apply this logic for re-locating the window when dragging to the RHS of the screen.

When dragging to the top left, it's a bit more complicated, I think the logic which offsets teh window to ensure that it is draggable will still need to be employed.

**Comment by WPFerg** [comment]
In that instance, we'll only need to check the top of the screen, and shunt downwards as appropriate I think.

**Comment by owennw** [comment]
Can you sneak the toolbar under the taskbar at the bottom? If so, that too.

**Comment by WPFerg** [comment]
If the taskbar's big, then yes.

**Comment by WPFerg** [comment]
Closed by #535

**Comment by ColinEberhardt** [comment]
@WPFerg things are a lot better, but it still 'shunts' in certain circumstances. With 9.2, if you drag out a tile to the bottom of the screen, it is 'shunted' upwards so that window is completely on screen.

Dragging to the right edge of the screen doesn't cause a shunt

**Comment by WPFerg** [comment]
This is because in the event of a large taskbar, you can tear out such that the moveable area would be underneath the taskbar.

**Comment by owennw** [comment]
Would we would sooner have the window repositioned like so, or allow a new window to spawn in a location where it cannot be dragged?

Perhaps there is some conditional middle ground if either seem too extreme.

**Comment by ColinEberhardt** [comment]
@owennw - we did the 'what would chrome do' test, and will copy the behaviour observed. Chrome allows you to drag a window so that it is beneath the taskbar, and we will allow the same!

**Comment by owennw** [comment]
While the main chrome window does that on moving it, tearing out a tab below the taskbar does not behave like that. Instead it initialises a new chrome window as full screen.

Given this issue is specifically about tearing out I'd suggest leaving in the shunt.

**Comment by ColinEberhardt** [comment]
@owennw let's discuss on Wednesday - I really don't like the shunt!

**Comment by rmarcalo** [comment]
I think the shunt when moving to the top of the screen is normal and acceptable (present on Chrome and Safari). To the bottom however, I don't think this as ideal and since we introduce a full draggable area on top, we don't need to enforce a shunt to prevent windows from being accessible. In my testing with the app and Chrome I don't see how one could drag the window under the taskbar(even a big one), covering the draggeable area, it just doesn't let me move the cursor beyond the bar.

**Comment by owennw** [comment]
That might depend on OS and windows version. On my Windows 10 machine I'm certainly able to do so. 
![under_taskbar](https://cloud.githubusercontent.com/assets/14889759/13667826/614ce1ec-e6b0-11e5-8d59-92d0b427277c.png)

**Comment by rmarcalo** [comment]
Would it be possible to have a shunt that is only triggered when the draggable area goes underneath the taskbar (this would make sure we cover all windows versions)? Even so I would align the window so that only that draggable area is visible right on top of the taskbar (since the user doing this seems to want that window to be somewhat hidden).

**Comment by ColinEberhardt** [comment]
@owennw as discussed yesterday, I think we should use Chrome as a guide here, and yes, I can drag it under (a massively oversized) task bar:

![image](https://cloud.githubusercontent.com/assets/1098110/13668032/dbfcf890-e6b1-11e5-9a4b-2b74e0adff49.png)
