### ISSUE TITLE
Favourites can be removed from within the search view without confirmation

### ISSUE THREAD

**Issue by akhmorgan** [ScottLogic/StockFlux#517]
I'm not sure if this is desired behaviour or not. Is it?

**Comment by akhmorgan** [comment]
should be an easy fix once the star refactor is merged, if this is not the desired behaviour.

**Comment by owennw** [comment]
Yes that was part of the original design spec. 

Originally there was to be a notification icon next to the favourite icon on a favourite card. The UX thought was that given the icons are quite small it was feasible for a used to click the wrong one, leading them to inadvertently remove a favourite, so the fix was to add the confirmation window. However, no sensible use case was presented for a notification (given we have fairly static data) so it was never added. On the search tab there is no such other icon, and the star is larger, so there is no confirmation.

**Comment by akhmorgan** [comment]
It should be easy to just put the same confirmation logic on the search as is applied on the favourites view though. So if it's a favourite, you get a confirmation. I'm happy to leave as is though, if that's the way it's supposed to be. It just seems a bit strange that in one place you get a warning before removing a favourite and in another, you don't.

**Comment by owennw** [comment]
If anything given no neighbouring icons on the favourites tab I'd lean towards not having a confirmation window at all. 

However, these decisions are under the remit of UX, not us, I think.

**Comment by bjedrzejewski** [comment]
Part of the original design spec.
