### ISSUE TITLE
Not clear that the scrollbar is a scroll bar

### ISSUE THREAD

**Issue by owennw** [ScottLogic/StockFlux#532]
It's dark, and on the left

**Comment by rmarcalo** [comment]
Due to the overall structure of the menus, it makes more sense to have it on the left. I think usability-wise this scrollbar won't bring any issues, as scrollbars are becoming increasingly obscured (in some applications even non-existent). Perhaps if we get confirmed feedback that it poses a problem we can revisit it?

**Comment by owennw** [comment]
I'm so used to it that I don't mind it at all. The original comment for this issue came from someone new in the office using the app and asking what the object was and what it did (which surprised me).

**Comment by rmarcalo** [comment]
I've had no issues (not even hesitation) with scrolling with any of the people I tested yesterday - the task didn't even mention scrolling it simply required it. I think it should be safe to assume for now that this isn't a general usability issue.

**Comment by owennw** [comment]
I'll close it then.
