### ISSUE TITLE
Fail gracefully if Quandl times out

### ISSUE THREAD

**Issue by owennw** [ScottLogic/StockFlux#574]

**Comment by owennw** [comment]
See #70 - make sure we gracefully fail if there is an incorrect API kye

**Comment by mbssantos** [comment]
Could be useful to clarify what to do when:

- Quandl down on start
- Quandl goes down mid use
- Single / some requests fail during use
- Wrong API key used || request limit exceeded

Logic I implemented tries a normal request and:
- If that fails, we try using a fallback option: 
 - Currently an anonymous request but can be easily changed to use a backup key since there's the 50 / day request limit
- If that one also fails the error message is shown to the user on the favorites bar

**Comment by WPFerg** [comment]
Regarding the first two, the long term plan is to have a set of backup data to use in that instance (#559), but that's an 'epic', so in the interim I'd group it with some requests fail.

If some requests fail, I think some form of ratio over time might be good. Say (for example) if >30% fail within 5 minutes, that would be a decent indicator to show a message about difficulties getting data. Or, simpler, if a request fails, show an error; and on the next succeeding request, hide that error.

The fallback for API/request limit seem to be okay to me.
