### ISSUE TITLE
Drag from the whole card rather than just the little triangle

### ISSUE THREAD

**Issue by bjedrzejewski** [ScottLogic/StockFlux#609]
Two more users complained and couldn't figure out how to drag a window.

We really should make the whole card dragable for tearout.

**Comment by rmarcalo** [comment]
In this case we'd remove the drag handle and reposition the Favourite icon. This is something I've been thinking about since earlier releases but was waiting for some feedback before suggesting it. My only concern is that people will move the cards by mistake, but I'd like to actually test that interaction.

**Comment by rmarcalo** [comment]
From my user testings yesterday this is clearly an important thing to change (and the single most important usability issue with the application). I included the handle to avoid mistakes, but I find that it simply is the natural interaction that people expect, and mistakes will be very unlikely. 

I will make a few tweaks to the visuals of the cards (which I will include in another issue) and remove the drag handles, expecting the dragging functionality to change to the whole card.

**Comment by rmarcalo** [comment]
I design the new cards in issue #685 .
