### ISSUE TITLE
Cap the number of favourites per window?

### ISSUE THREAD

**Issue by WPFerg** [ScottLogic/StockFlux#614]
Should the number of favourites per window be capped to help prevent the application slowing down/misuse of the Quandl API? Having 200-300+ favourites per window seems a bit silly.

**Comment by rmarcalo** [comment]
I can't imagine a window being useful after 10 stocks. This is an entirely arbitrary number, but I find it unlikely to be reached in most cases.

**Comment by owennw** [comment]
@rmarcalo How should this work? When 10 (or n) stocks have been selected as favourite what do we do?

We can disable all favourite stars on new search results, or display a message. Or allow adding new stocks but remove the eldest ones?

**Comment by owennw** [comment]
Similarly how would this work for tearing in? If a window has the maximum number of stocks do we disallow tearing in? I.e. don't show the hover state, and when the user lets go of the torn out stock a new window is opened.

**Comment by bjedrzejewski** [comment]
I really don't see the point of this feature. I Often have at least 20 favorites in my stockflux, but I wouldn't want to prevent others from having more.

**Comment by bjedrzejewski** [comment]
It's adding complication and limiting functionality for no great reason in my opinion.

**Comment by rmarcalo** [comment]
Honestly I having a huge number of stocks favourited isn't really what the application was designed for, but it probably doesn't hurt. It reduces de incentive to create new windows, which is an openfin feature we wanted to highlight, but usability-wise, having to create new windows isn't a great workflow to encourage. With this in mind, not adding a limit might be best at least for now, since it gives control to the user.
