### ISSUE TITLE
Remove 'development' traffic from Google Analytics

### ISSUE THREAD

**Issue by ColinEberhardt** [ScottLogic/StockFlux#777]
Currently we capture all traffic, which creates quite a bit of noise in our GA reports. I'd propose removing all dev traffic, which I think is currently captured simply as `index.html`.

 - [x] Remove dev traffic
 - [ ] Potentially clean up the reports ... can we delete the old data that we no longer want?
 - [ ] Add a very brief document to the repo that describes GA usage, i.e. where events are captured, how traffic from the different reelases is captured.

**Comment by mbssantos** [comment]
- Remove dev traffic -> Since our subnets are filtered out (#766) we'll only get traffic to /index.html from people who build and run it outside SL . Do we also want to filter that out?
- Clean up reports -> It does not seem possible to delete _part_ of the data, we can only delete everything
- Document describing GA usage -> writting it now

**Comment by mbssantos** [comment]
Updated GA with individual IP filters as discussed.
Should we go ahead and delete all the data?

**Comment by ColinEberhardt** [comment]
sure - go for it!

**Comment by mbssantos** [comment]
Instead of deleting the old view, I've copied it and made a new one.
When we're happy everything is working fine we can delete the old.
